### ISSUE TITLE
Torch not illuminating mobs

### ISSUE THREAD

**Issue by bloodmoon14** [Redi2Go/PhotonicEngine#111] opened 2024-11-28 23:52 UTC
Mobs are not being illuminated by torches leading to them looking black
![Screenshot 2024-11-29 102141](https://github.com/user-attachments/assets/aa3216c7-582b-4395-92c9-9280bda10df7)

**Comment by Redi2Go** [comment] 2024-11-29 23:50
Duplicate of #51

**Closed as completed by Redi2Go** 2024-11-29 23:50 UTC
Labels: wontfix

**Comment by thijsi123** [comment] 2025-01-20 20:30
> Duplicate of [#51](https://github.com/Redi2Go/PhotonicEngine/issues/51)


Hey, just a question. Is this till being worked on?

**Comment by Redi2Go** [comment] 2025-01-23 09:22
It should be fixed with the next release, which will still need a couple of weeks
