### ISSUE TITLE
Corrupted textures (?) on AMD GPU, Minecraft 1.21.1, Linux 6.11.6

### ISSUE THREAD

**Issue by ImSapphire** [Redi2Go/PhotonicEngine#90] opened 2024-11-09 23:16 UTC
When using Photonics with the recommended BSL shader version, it seems like most block textures are corrupted. Also affects lighting through glass panes.

Using an AMD Radeon RX 7700 XT (amdgpu kernel driver, Mesa 24.2.6) on Fedora Linux 41 (Kernel 6.11.6)
![2024-11-09_17 14 00](https://github.com/user-attachments/assets/48be77b7-d27c-45df-b86b-4489913fc251)
![2024-11-09_17 14 07](https://github.com/user-attachments/assets/015cabfd-9114-4588-8b07-4301e41ffd75)
![2024-11-09_17 15 02](https://github.com/user-attachments/assets/8b9b78c9-11e7-4d3e-a0ac-8e95e6b8aff7)
Log: https://mclo.gs/pJTXfMr

**Comment by Redi2Go** [comment] 2024-11-10 09:49
Hi, thank you for reporting this issue. It's a known bug that occurs because of voxel-based rendering, which will be replaced in the next release.

Duplicate of #48

**Closed as completed by Redi2Go** 2024-11-10 09:49 UTC
