### ISSUE TITLE
Broken textures

### ISSUE THREAD

**Issue by Oregano1963** [Redi2Go/PhotonicEngine#48] opened 2024-10-06 04:37 UTC
![2024-10-06_00 28 41](https://github.com/user-attachments/assets/eb1d11a5-8a5e-473e-8691-2e45447efe17)
![2024-08-16_00 40 32](https://github.com/user-attachments/assets/2cbffa18-b3c2-403a-8ad1-e22ea5769cba)

For some reason, a bunch of textures are broken. This happens with a whole litany of blocks like wood, certain flowers, and stone.

Linux Mint 21.3
7900xtx
I'm om the version you gave me for the broken texture issue.

**Comment by Redi2Go** [comment] 2024-10-07 05:31
Do you have any clues, what might have caused that? I will see if I can reproduce the bug, otherwise I will have a very hard time diagnosing your issue.

**Comment by Oregano1963** [comment] 2024-10-07 19:56
I have no clues at all. It seems to be random which textures are bricked and it persists even when I redownload the mod.

**Comment by Jozhin-s-Bazhin** [comment] 2024-10-27 08:09
I have the same issue on NixOS with a 7700S. It happens both on the alpha and the beta.

**Comment by Stargate256** [comment] 2024-10-27 08:22
Same issue on Archlinux with wayland on rx6800xt. The only line in logs that is indicating something is wrong is:

"[09:20:45] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program."

**Comment by 69NoraV** [comment] 2024-10-27 10:27
I have the same issue on arch linux with a 6650xt, the raytracing is perfect but the textures are all over the place. Could be a problem linked to java 3d rendering on linux maybe?

**Comment by i3vie** [comment] 2024-10-27 17:33
I have the same issue on Arch with an RX 6600 XT. rendering looks mostly fine. Trees are made of ice and snow, and stained glass is solid.
![image](https://github.com/user-attachments/assets/0c2455c1-01da-4699-85b4-2dd3083a5258)
<details>
<summary> Game version information </summary>

- Minecraft 1.21.1
- Fabric 0.16.7

</details>
<details>
<summary> Mod version information </summary>

- Fabric API 0.102.0+1.21.1
- Iris 1.7.3+mc1.21
- Mod Menu 11.0.3
- Photonic 0.2.4
- Placeholder API 2.4.1+1.21
- Reese's Sodium Options 1.7.3+mc1.21
- Sodium 0.5.11+mc1.21

</details>
<details>
<summary> Graphics driver information </summary>
AMD RX 6600 XT using AMDGPU driver

```
pacman -Qi xf86-video-amdgpu

Name            : xf86-video-amdgpu
Version         : 23.0.0-2
Description     : X.org amdgpu video driver
Architecture    : x86_64
```
```
uname -a

Linux i3varch 6.11.5-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Tue, 22 Oct 2024 18:31:33 +0000 x86_64 GNU/Linux
```

</details>

**Comment by Oregano1963** [comment] 2024-10-27 17:39
Why is there so much activity here now? Did a youtuber cover this mod or something?

**Comment by Jozhin-s-Bazhin** [comment] 2024-10-27 17:42
Yes

**Comment by kxxzo** [comment] 2024-10-27 18:38
> J'ai le même problème sur Arch avec une RX 6600 XT. Le rendu est globalement correct. Les arbres sont faits de glace et de neige, et les vitraux sont solides. ![image](https://private-user-images.githubusercontent.com/180745311/380517315-0c2455c1-01da-4699-85b4-2dd3083a5258.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwNTQ0MTMsIm5iZiI6MTczMDA1NDExMywicGF0aCI6Ii8xODA3NDUzMTEvMzgwNTE3MzE1LTBjMjQ1NWMxLTAxZGEtNDY5OS04NWI0LTJkZDMwODNhNTI1OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyN1QxODM1MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOGFhYTQ2Yzk4ODg5ZDE4MDY4NzczNTgyMTgwNjAxODM4YTFlNzY5OWE4NGVmZWU1MDNhOTQzMDIxNTJiY2JhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kGNLPdgM8iEIP_ofl-GhtxUUmS9eLkClPdrdevMaie8)
> 
> Informations sur la version du jeu
> Informations sur la version du module
> Informations sur le pilote graphique

I think opaque glass is normal because transparency isn't supported

**Comment by awumii** [comment] 2024-10-27 18:48
I can also reproduce this on Arch Linux with Mesa 24.2.5 and 24.3-devel, Radeon RX 6600 XT.
Interestingly, this issue is not present when using software rendering (llvmpipe driver). This can be enabled by setting `LIBGL_ALWAYS_SOFTWARE=true` but the performance is abysmal, obviously.
![obraz](https://github.com/user-attachments/assets/72e2a2ee-619c-4a4e-828a-3a43442d2056)
This issue also happens under the Zink driver.

UPDATE: When enabling mesa debug the following error appears:
```
Mesa: error: GL_INVALID_OPERATION in glBindTextureUnit(non-gen name)
[19:49:06] [Render thread/INFO]: OpenGL debug message: id=2, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION in glBindTextureUnit(non-gen name)'
```

**Comment by Fxsch** [comment] 2024-10-30 21:04
I have the same issue. I'm on Fedora Linux 41 and have an AMD RX 6700XT. The version of Mesa I have installed is `24.2.4`.

I also noticed that my hand isn't moving at all, even though "View bobbing" is activated. Is that happening for you all too or is that something separate that I should open its own issue for?

**Comment by Redi2Go** [comment] 2024-10-31 14:56
View Bobbing is manually disabled by me, because I cannot get it working properly. You can create an issue, but you have to keep in mind, that it is very low priority to me.

Regarding the broken textures: I am currently working on a fix and I will be releasing a patched version here as soon as I can. Has anyone else here seen that issue outside of an AmdGPU/Linux setup? Thank you for your feedback!

**Comment by Redi2Go** [comment] 2024-10-31 19:01
As @DennisWReece1 mentioned on Twitter, it also doesn't work on SteamDeck

**Comment by theRookieCoder** [comment] 2024-11-01 14:58
Fedora Linux user here with an AMD iGPU (Radeon 780M). Here's a screenshot of debug mode, 90% of blocks look like this.
![2024-11-01_20 25 51](https://github.com/user-attachments/assets/ef003222-f6db-4de5-becd-238054c3864f)

At first I thought it's something to do with non-full blocks, but even regular old cobblestone has the same issue.

**Comment by oDEVU** [comment] 2024-11-01 17:50
Same on fedora + rx6800 + Mesa 24.2.5, the error says `Mesa: error: GL_INVALID_OPERATION in glBindTextureUnit` i might be retarded but on screenshots of the game running on nvidia hardware it says its using OpenGL version that doesnt even support this function ( 3.2.0 which isnt even suported by sodium, and khronos website says this function is suported on OpenGL 4.5 and up) same on AMD hardware on windows (it also says 3.2.0) while on AMD+Linux it shows 4.6 (core profile). Whats even wierder every world has diffrent textures broken, i was able to create a world when only birch leaves and stone was glitched but some worlds had every possible texture glitched. Also leaves placed by player are not glitched but other blocks i tried are.

Edit: I tried to force mesa to use open gl 3.2 and 3.3, it didn't fixed it, I even tried ZINK still no effect. I tried to help but im too dumb

**Comment by Redi2Go** [comment] 2024-11-07 22:16
I have a very hard time reproducing this bug and I have decided to deprecate the voxel-rendering approach (meaning that I will use normal triangle-based raytracing). I will close this issue as "won't fix" because the rendering will be replaced anyway.

**Closed as completed by Redi2Go** 2024-11-07 22:16 UTC
Labels: bug, wontfix
