### ISSUE TITLE
Rendering issue with certain blocks

### ISSUE THREAD

**Issue by extremjaws** [Redi2Go/PhotonicEngine#96] opened 2024-11-10 23:08 UTC
Hello, I'm having an odd issue where some blocks are rendering with the incorrect textures. Some of these blocks include stone, sand, birch logs, seagrass, and glow lichen to name a few. I am running Linux with open-source video drivers, so a video driver issue wouldn't be out of the question. However, I've never had issues with raytracing like this.

I'm running:

- Minecraft 1.20.6
- Java 21.0.5
- Photonic 0.2.3
- Iris 1.7.2
- Sodium 0.5.11
- Fabric Loader 0.16.9
- Video driver: Mesa 24.2.6-arch1.1

Here's some screenshots of the issue and my hardware (The RTX 3050 is not in use here):
![2024-11-10_15 55 02](https://github.com/user-attachments/assets/456937ae-ec5c-4a26-bb50-7aa510183ab5)
![2024-11-10_15 55 09](https://github.com/user-attachments/assets/86ea6e98-1504-4b83-b2c9-d9977611b074)
![2024-11-10_15 55 42](https://github.com/user-attachments/assets/eef8be11-09e9-4451-8e7a-850b746b32bd)
![2024-11-10_15 56 07](https://github.com/user-attachments/assets/70c029f0-6b95-4415-ba31-c58d04ded8fd)
![image](https://github.com/user-attachments/assets/c5ef77e9-8d82-4ff9-9899-4f23d70ac31c)

Thank You!

**Comment by Redi2Go** [comment] 2024-11-12 18:51
Hi, thank you for reporting. Unfortunately I have a very hard time reproducing this bug, so there is no quick fix going out for this issue. Rendering will fundamentally change with the next release, which will indirectly fix your issue. So I will mark this as a "won't fix"

Duplicate of #48

**Closed as completed by Redi2Go** 2024-11-12 18:51 UTC
Labels: wontfix
