### ISSUE TITLE
0.2.5 version of the mod for 1.20.1 and 1.20.4 doesn´t work

### ISSUE THREAD

**Issue by victor176S** [Redi2Go/PhotonicEngine#94] opened 2024-11-10 15:46 UTC
Versions 1.20.1 and 1.20.4 of the mod doesn´t work (gives error code 1) with its corresponding dependencies 

(before testing anything, i tried to open another mods like sodium with iris or others without photonic to make sure is not a problem caused by me)

1.20.1 was tested with:

![image](https://github.com/user-attachments/assets/338fc940-9b86-49ba-8309-91d5e6e4cb96)

i tested without indium too and the corresponding version of embeddium that is the equivalent to sodium 0.5.11, separately

the log, if it helps: [latest.log](https://github.com/user-attachments/files/17691971/latest.log)

1.20.4 was tested with:

![image](https://github.com/user-attachments/assets/8deb9293-1433-4923-9ceb-aff4377505e1)

i tested without indium too and the corresponding version of embeddium that is the equivalent to sodium 0.5.8 (which is the latest for 1.20.4), separately 

the log, if it helps: [latest.log](https://github.com/user-attachments/files/17691961/latest.log)

if other stuff is needed im glad to help, this mod is awesome :)

**Comment by Redi2Go** [comment] 2024-11-10 16:17
You need Java 22 for it to work. This will be fixed in the next version

Duplicate of #89

**Closed as completed by Redi2Go** 2024-11-10 16:17 UTC
