### ISSUE TITLE
Some blocks doesn't emit light

### ISSUE THREAD

**Issue by k0nfig15** [Redi2Go/PhotonicEngine#40] opened 2024-07-28 09:30 UTC
There are some blocks which should emit light but they don't.
![2024-07-28_11 23 52](https://github.com/user-attachments/assets/51857739-5840-41b9-b62d-7b3133de3641)
I get why ender chest doesn't emit light, but candels, froglights or light block should emit some light.

**Comment by Redi2Go** [comment] 2024-07-28 10:41
Thank you for reporting this issue.
This will be fixed in the next release.

**Comment by nitanmarcel** [comment] 2024-07-29 11:47
> Thank you for reporting this issue. This will be fixed in the next release.

Just of curiosity. What's the changelog for the next update?

**Comment by Redi2Go** [comment] 2024-07-29 13:40
Render Distance increased to 15 chunks
Shadow Mapping Support: Entities cast shadows on terrain and vice versa (Meaning Distant Horizon works properly + Light Shafts + Cloud Shadows)

I'm currently working on fixing performance issues, that were caused by Shadow Mapping

**Comment by nitanmarcel** [comment] 2024-07-29 14:29
> Render Distance increased to 15 chunks Shadow Mapping Support: Entities cast shadows on terrain and vice versa (Meaning Distant Horizon works properly + Light Shafts + Cloud Shadows)
> 
> I'm currently working on fixing performance issues, that were caused by Shadow Mapping

Awesome. Can't wait for the release ^^

**Closed as completed** 2024-07-30 19:07 UTC
Labels: bug
